### ISSUE TITLE
Not creating make file to compile on windows

### ISSUE THREAD

**Issue by katrejos** [hunter-packages/onmt#1]
![image](https://user-images.githubusercontent.com/46461847/55523613-37c78480-5647-11e9-8e47-a1d09e99a60f.png)

I'm not getting the .dll because something's missing after cmake, I already have installed eigen, boost, MKL and referred them in variables, actually cmake is not flagging errors. Any ideas why this might be?

**Comment by ruslo** [comment]
> Not creating make file to compile on windows

Because you're using Visual Studio generator, there will be no Makefile and you can't do `make`.

**Comment by katrejos** [comment]
Thanks, is there a way to generate that .dll from there?

**Comment by ruslo** [comment]
Try to generate the project with [BUILD_SHARED_LIBS=ON](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) and use standard CMake instructions. Also, I'm not sure if it will help, I'm not an active user of this project.

**Comment by ruslo** [comment]
Closing inactive discussion.
